POST http://localhost:5000/api/add HTTP/1.1
content-type: application/json

{
    "feature_1": 50,
    "feature_2": 52,
    "feature_3": 54,
    "feature_4": 56,
    "feature_5": 58
}

###

GET http://localhost:5000/check HTTP/1.1

###

POST http://localhost:5000/api/fit HTTP/1.1
content-type: application/json

###

POST http://localhost:5000/api/predict HTTP/1.1
content-type: application/json

{
    "feature_1": -2.16598884,
    "feature_2": 1.77802055,
    "feature_3": 1.76029229,
    "feature_4": 1.12918106,
    "feature_5": 1.55158756
}